<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>reqs</string>
		<string>requirements</string>
	</array>
	<key>name</key>
	<string>Reqs</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>^\[.*\]</string>
			<key>name</key>
			<string>constant.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\W.-\s.*</string>
			<key>name</key>
			<string>keyword.operator.word</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(--[^\s]+){1}</string>
			<key>name</key>
			<string>storage.type</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\#[^\s]*</string>
			<key>name</key>
			<string>entity.name</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\@[^\s]*</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\(.*\)</string>
			<key>name</key>
			<string>variable.language</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>text.requirements</string>
	<key>uuid</key>
	<string>94273595-e914-4678-8e7d-0b99e9a03ff5</string>
</dict>
</plist>
